language: python

cache: pip

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="lua 5.4"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  - luarocks install busted

install:
  - luarocks make

script:
  - busted
